version: '3.8'

services:
  metabase:
    image: metabase/metabase
    container_name: metabase
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
    volumes:
      - metabase-data:/metabase-data

volumes:
  metabase-data:
